server:
  port: 8888
  version: v1

spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      # 配置默认数据源
      primary: primary
      datasource:
        primary:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/course_accreditation?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=UTF-8

web:
  # Swagger相关配置
  swagger:
    basePackage: com.excellent.accreditation
    title: ACCREDITATION VUE API
    description: ACCREDITATION VUE API Document.
    version: 1.0
    author: evildoer
    url: https://baidu.com
    email: 123456@qq.com
    license: Apache 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html

#pagehelper分页插件配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#mybatis plus 设置
mybatis-plus:
  global-config:
    banner: false





# course,course_class,course_target,graduation_demand,graduation_point,major,questionnaire,select_couse,self_evaluation,semester,student,supporting_course,teacher